### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Raynos** [qualiancy/drip#1]
It's unfair to have shiny auto-generated documentation but not share the tool that builds it.

**Comment by logicalparadox** [comment]
Haha. Your reminded me docs were way behind. Anyway...

New docs are up: http://alogicalparadox.com/drip/

And your right, its quite unfair... so here it is.

The tool is called Codex (https://github.com/logicalparadox/codex). Its code is a bit of a mess currently, but it gets the job done. If you look in the `docs` folder for drip you will see how I set everything up. Stay tuned on Codex for more details. 

Cheers.
