### ISSUE TITLE
Difference from eventEmitter2?

### ISSUE THREAD

**Issue by Charuru** [qualiancy/drip#2]
How is this different from something like this:

https://github.com/hij1nx/EventEmitter2

**Comment by logicalparadox** [comment]
Practically, its not much different at this point. Some features were added to be directly api compatible. But I also have a few features in the pipeline that will be unique vs ee2, but they aren't a primary focus of mine at this point. Namely, ensure no duplicate functions for any given event... and turn off entire threads in the listener hierarchy when wildcarded (right now .off() looks for exact match to when you called .on() ).

Philosophically, (1) it was a good learning experience and fun building (2) i wanted to make sure that if something needed to be tweaked i had the ability to do so and deploy. (3) I use it almost everywhere ... so sometimes you just want to build something yourself :)
